services:
  postgres:
    image: postgres:16
    container_name: fleet-postgres
    environment:
      POSTGRES_DB: fleetdb
      POSTGRES_USER: fleet_user
      POSTGRES_PASSWORD: fleet_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fleet-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/fleetdb
      - SPRING_DATASOURCE_USERNAME=fleet_user
      - SPRING_DATASOURCE_PASSWORD=fleet_password
      - SPRING_FLYWAY_ENABLED=true
    depends_on:
      - postgres

volumes:
  postgres-data: